/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19helpline;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class coviddateselect extends javax.swing.JFrame {

    int flag = 0;
    public Connection connection;
    public Statement stmt;

    public coviddateselect() {
        initComponents();
    }

    String usid, covstatus, afdate;

    public coviddateselect(String msg) {
        initComponents();
        usid = msg;

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=COVID19 Helpline;selectMethod=cursor", "sa", "123456");

            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM Userr WHERE UserId = '" + usid + "'");

            if (resultSet.next()) {

                covstatus = resultSet.getString("UserCovidStatus");
                afdate = resultSet.getString("UserAffectedDate");

                if (covstatus.equals("Affected")) {
                    jLabel1.setVisible(true);
                    useraffecteddateLabel.setVisible(false);
                    affectdate.setVisible(false);
                    flag = 1;
                } else {
                    jLabel1.setVisible(false);

                }

            }

            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        useraffecteddateLabel = new javax.swing.JLabel();
        userrecoverydateLabel = new javax.swing.JLabel();
        submitbutton = new javax.swing.JButton();
        backuserprofilebutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        affectdate = new com.toedter.calendar.JDateChooser();
        recoverydate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        useraffecteddateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        useraffecteddateLabel.setText("Covid19 Affected Date:");

        userrecoverydateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userrecoverydateLabel.setText("Covid19 Recovery Date:");

        submitbutton.setBackground(new java.awt.Color(0, 153, 255));
        submitbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        submitbutton.setForeground(new java.awt.Color(255, 255, 255));
        submitbutton.setText("SUBMIT");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        backuserprofilebutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backuserprofilebutton.setText("Back To User Profile");
        backuserprofilebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backuserprofilebuttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("If you are recovered now, please update the recovered date.");

        affectdate.setDateFormatString("yyyy-MM-dd");

        recoverydate.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(useraffecteddateLabel)
                    .addComponent(userrecoverydateLabel))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(affectdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recoverydate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(138, 138, 138))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(294, 294, 294))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backuserprofilebutton)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(138, 138, 138))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(useraffecteddateLabel)
                    .addComponent(affectdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userrecoverydateLabel)
                    .addComponent(recoverydate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(backuserprofilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backuserprofilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backuserprofilebuttonActionPerformed
        setVisible(false);
        UserProfile up = new UserProfile(usid);
        up.setVisible(true);
    }//GEN-LAST:event_backuserprofilebuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:

        if (flag == 0) {
            String date1 = ((JTextField) affectdate.getDateEditor().getUiComponent()).getText();
            String date2 = ((JTextField) recoverydate.getDateEditor().getUiComponent()).getText();
            String firstday = "2020-03-08";

            LocalDateTime currentDateTime = LocalDateTime.now();

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

            String today = currentDateTime.format(formatter);

            int x = date1.compareTo(firstday);
            int y = date1.compareTo(today);
            int a = date2.compareTo(date1);
            int b = date2.compareTo(today);

            if (date1.equals("")) {
                JOptionPane.showMessageDialog(this, "Please insert date");
            } // Get current date time
            else if (x < 0 || y > 0) {
                JOptionPane.showMessageDialog(this, "Please check again your affected date");
            } else if (date2.equals("")) {
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    connection = DriverManager.getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=COVID19 Helpline;selectMethod=cursor", "sa", "123456");

                    System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

                    String Affected = "Affected";
                    stmt = connection.createStatement();
                    String sq = "UPDATE USERR SET UserCovidStatus = '" + Affected + "' , UserAffectedDate='" + date1 + "' WHERE UserId = '" + usid + "'";
                    stmt.executeUpdate(sq);

                    setVisible(false);
                    UserProfile up = new UserProfile(usid);
                    up.setVisible(true);

                    connection.close();
                } catch (SQLException ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else if (a <= 0 || b > 0) {
                JOptionPane.showMessageDialog(this, "Please check again your recovered date");
            } else {

                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    connection = DriverManager.getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=COVID19 Helpline;selectMethod=cursor", "sa", "123456");

                    System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

                    String Affected = "Affected";
                    stmt = connection.createStatement();
                    String sq = "UPDATE USERR SET UserCovidStatus = '" + Affected + "' , UserAffectedDate='" + date1 + "', UserRecoveryDate='" + date2 + "' WHERE UserId = '" + usid + "'";
                    stmt.executeUpdate(sq);

                    setVisible(false);
                    UserProfile up = new UserProfile(usid);
                    up.setVisible(true);

                    connection.close();
                } catch (SQLException ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        } else {

            String date2 = ((JTextField) recoverydate.getDateEditor().getUiComponent()).getText();

            LocalDateTime currentDateTime = LocalDateTime.now();

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

            String today = currentDateTime.format(formatter);

            if (date2.equals("")) {
                setVisible(false);
                UserProfile up = new UserProfile(usid);
                up.setVisible(true);
            } else {

                int x = date2.compareTo(today);
                int y = date2.compareTo(afdate);

                if (y <= 0 || x > 0) {
                    JOptionPane.showMessageDialog(this, "Please check again your recovered date");
                } else {
                    try {
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                        connection = DriverManager.getConnection(
                                "jdbc:sqlserver://localhost:1433;databaseName=COVID19 Helpline;selectMethod=cursor", "sa", "123456");

                        System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

                        stmt = connection.createStatement();
                        String sq = "UPDATE USERR SET  UserRecoveryDate='" + date2 + "' WHERE UserId = '" + usid + "'";
                        stmt.executeUpdate(sq);

                        setVisible(false);
                        UserProfile up = new UserProfile(usid);
                        up.setVisible(true);

                        connection.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

        }


    }//GEN-LAST:event_submitbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coviddateselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coviddateselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coviddateselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coviddateselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coviddateselect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser affectdate;
    private javax.swing.JButton backuserprofilebutton;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JDateChooser recoverydate;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel useraffecteddateLabel;
    private javax.swing.JLabel userrecoverydateLabel;
    // End of variables declaration//GEN-END:variables
}
