/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19helpline;

/**
 *
 * @author USER
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public String usid;
    public dashboard() {
        initComponents();
    }
    
    public dashboard(String mg){
        initComponents();
        usid=mg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UserProfileButton = new javax.swing.JButton();
        HospitalInformationButton = new javax.swing.JButton();
        AmbulanceInformationButton = new javax.swing.JButton();
        DoctorInformationButton = new javax.swing.JButton();
        SearchForPlasmaButton = new javax.swing.JButton();
        OxygenProviderInformationButton = new javax.swing.JButton();
        ICUInformationButton = new javax.swing.JButton();
        AboutUsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Welcome To COVID-19 Helpline");

        UserProfileButton.setBackground(new java.awt.Color(0, 204, 255));
        UserProfileButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        UserProfileButton.setText("User Profile");
        UserProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserProfileButtonActionPerformed(evt);
            }
        });

        HospitalInformationButton.setBackground(new java.awt.Color(0, 204, 255));
        HospitalInformationButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        HospitalInformationButton.setText("Hospital Information");
        HospitalInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalInformationButtonActionPerformed(evt);
            }
        });

        AmbulanceInformationButton.setBackground(new java.awt.Color(0, 204, 255));
        AmbulanceInformationButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        AmbulanceInformationButton.setText("Ambulance Information");
        AmbulanceInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmbulanceInformationButtonActionPerformed(evt);
            }
        });

        DoctorInformationButton.setBackground(new java.awt.Color(0, 204, 255));
        DoctorInformationButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        DoctorInformationButton.setText("Doctor Information");
        DoctorInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorInformationButtonActionPerformed(evt);
            }
        });

        SearchForPlasmaButton.setBackground(new java.awt.Color(0, 204, 255));
        SearchForPlasmaButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        SearchForPlasmaButton.setText("Search For Plasma");
        SearchForPlasmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchForPlasmaButtonActionPerformed(evt);
            }
        });

        OxygenProviderInformationButton.setBackground(new java.awt.Color(0, 204, 255));
        OxygenProviderInformationButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        OxygenProviderInformationButton.setText("Oxygen Provider Information");
        OxygenProviderInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OxygenProviderInformationButtonActionPerformed(evt);
            }
        });

        ICUInformationButton.setBackground(new java.awt.Color(0, 204, 255));
        ICUInformationButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        ICUInformationButton.setText("ICU Information");
        ICUInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICUInformationButtonActionPerformed(evt);
            }
        });

        AboutUsButton.setBackground(new java.awt.Color(0, 204, 255));
        AboutUsButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        AboutUsButton.setText("About Us");
        AboutUsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 102, 102));
        logoutButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoctorInformationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ICUInformationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AboutUsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(HospitalInformationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                            .addComponent(SearchForPlasmaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AmbulanceInformationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OxygenProviderInformationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(229, 229, 229))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserProfileButton)
                    .addComponent(HospitalInformationButton))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorInformationButton)
                    .addComponent(SearchForPlasmaButton))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ICUInformationButton)
                    .addComponent(AmbulanceInformationButton))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OxygenProviderInformationButton)
                    .addComponent(AboutUsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AmbulanceInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmbulanceInformationButtonActionPerformed
        setVisible(false);
        AmbulanceInformation hi=new AmbulanceInformation(usid);
        hi.setVisible(true);
    }//GEN-LAST:event_AmbulanceInformationButtonActionPerformed

    private void ICUInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICUInformationButtonActionPerformed
        setVisible(false);
        ICUInformation hi=new ICUInformation(usid);
        hi.setVisible(true);
    }//GEN-LAST:event_ICUInformationButtonActionPerformed

    private void HospitalInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalInformationButtonActionPerformed
        setVisible(false);
        HospitalInformation hi=new HospitalInformation(usid);
        hi.setVisible(true);
    }//GEN-LAST:event_HospitalInformationButtonActionPerformed

    private void UserProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserProfileButtonActionPerformed
        setVisible(false);
        new UserProfile(usid).setVisible(true);
    }//GEN-LAST:event_UserProfileButtonActionPerformed

    private void DoctorInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorInformationButtonActionPerformed
        setVisible(false);
        DoctorInformation di=new DoctorInformation(usid);
        di.setVisible(true);
    }//GEN-LAST:event_DoctorInformationButtonActionPerformed

    private void SearchForPlasmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchForPlasmaButtonActionPerformed
        setVisible(false);
        SearchForPlasma sfp=new SearchForPlasma(usid);
        sfp.setVisible(true);
    }//GEN-LAST:event_SearchForPlasmaButtonActionPerformed

    private void AboutUsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsButtonActionPerformed
        setVisible(false);
        AboutUs au=new AboutUs(usid);
        au.setVisible(true);
    }//GEN-LAST:event_AboutUsButtonActionPerformed

    private void OxygenProviderInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OxygenProviderInformationButtonActionPerformed
        setVisible(false);
        OxygenProviderInformation opi=new OxygenProviderInformation(usid);
        opi.setVisible(true);
    }//GEN-LAST:event_OxygenProviderInformationButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
       Login obj = new Login();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUsButton;
    private javax.swing.JButton AmbulanceInformationButton;
    private javax.swing.JButton DoctorInformationButton;
    private javax.swing.JButton HospitalInformationButton;
    private javax.swing.JButton ICUInformationButton;
    private javax.swing.JButton OxygenProviderInformationButton;
    private javax.swing.JButton SearchForPlasmaButton;
    private javax.swing.JButton UserProfileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
