/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19helpline;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author RDHXT
 */
public class SignUp extends javax.swing.JFrame {

    int cnt;
    int flag=0;
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        title = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usergenderLabel = new javax.swing.JLabel();
        userageLabel = new javax.swing.JLabel();
        userbloodgroupLabel = new javax.swing.JLabel();
        useraddressLabel = new javax.swing.JLabel();
        usermobileLabel = new javax.swing.JLabel();
        userpasswordLabel = new javax.swing.JLabel();
        userconfirmpasswordLabel = new javax.swing.JLabel();
        usernameTextfield = new javax.swing.JTextField();
        userageTextfield = new javax.swing.JTextField();
        usergenderTextfield = new javax.swing.JComboBox<>();
        useraddressTextfield = new javax.swing.JTextField();
        userbloodgroupTextfield = new javax.swing.JComboBox<>();
        usermobileTextfield = new javax.swing.JTextField();
        signupButton = new javax.swing.JButton();
        useremailLabel = new javax.swing.JLabel();
        useremailTextfield = new javax.swing.JTextField();
        backbutton = new javax.swing.JButton();
        userpasswordTextfield = new javax.swing.JPasswordField();
        userconfirmpasswordTextfield = new javax.swing.JPasswordField();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Gender:");

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        title.setForeground(new java.awt.Color(102, 102, 255));
        title.setText("Sign Up");

        usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usernameLabel.setText("Name:");

        usergenderLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usergenderLabel.setText("Gender:");

        userageLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userageLabel.setText("Age:");

        userbloodgroupLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userbloodgroupLabel.setText("Blood Group:");

        useraddressLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        useraddressLabel.setText("Address:");

        usermobileLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usermobileLabel.setText("Mobile No.:");

        userpasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userpasswordLabel.setText("Password:");

        userconfirmpasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userconfirmpasswordLabel.setText("Confirm Password:");

        usernameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextfieldActionPerformed(evt);
            }
        });

        usergenderTextfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", " " }));

        userbloodgroupTextfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-" }));

        signupButton.setBackground(new java.awt.Color(204, 204, 204));
        signupButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        signupButton.setForeground(new java.awt.Color(153, 153, 255));
        signupButton.setText("Sign Up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });

        useremailLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        useremailLabel.setText("Email:");

        backbutton.setBackground(new java.awt.Color(51, 204, 0));
        backbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 253, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(245, 245, 245))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backbutton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameLabel)
                                    .addComponent(usergenderLabel)
                                    .addComponent(userageLabel)
                                    .addComponent(useraddressLabel)
                                    .addComponent(userbloodgroupLabel)
                                    .addComponent(usermobileLabel)
                                    .addComponent(useremailLabel))
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(usermobileTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userbloodgroupTextfield, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(useraddressTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userageTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usergenderTextfield, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usernameTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(useremailTextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userpasswordLabel)
                                    .addComponent(userconfirmpasswordLabel))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userpasswordTextfield)
                                    .addComponent(userconfirmpasswordTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                        .addGap(15, 15, 15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signupButton)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useremailLabel)
                    .addComponent(useremailTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usergenderLabel)
                    .addComponent(usergenderTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userageLabel)
                    .addComponent(userageTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(useraddressLabel)
                    .addComponent(useraddressTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userbloodgroupLabel)
                    .addComponent(userbloodgroupTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usermobileLabel)
                    .addComponent(usermobileTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userpasswordLabel)
                    .addComponent(userpasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userconfirmpasswordLabel)
                    .addComponent(userconfirmpasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(signupButton)
                .addGap(21, 21, 21)
                .addComponent(backbutton)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Connection connection;
    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed

        String name = usernameTextfield.getText();
        String email = useremailTextfield.getText();
        String gender = (String) usergenderTextfield.getSelectedItem();
        String age = userageTextfield.getText();
        String address = useraddressTextfield.getText();
        String bloodgroup = (String) userbloodgroupTextfield.getSelectedItem();
        String mobile = usermobileTextfield.getText();
        String covidstatus = "Not Affected";

        String password = userpasswordTextfield.getText();
        String confirmpassword = userconfirmpasswordTextfield.getText();
        cnt = 0;

        //System.out.println(name+email+gender+age+address+bloodgroup+mobile+covidstatus);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=COVID19 Helpline;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());
            
            
            String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
            
            Boolean b = email.matches(EMAIL_REGEX);
            int uflag=0;
            int aflag=0;
            int mflag=0;
            
            if(age.length()>3)
                aflag=1;
            
            for(int i=0 ; i<age.length() ; i++){
                char c= age.charAt(i);
                
                if(c>='0' && c<='9')
                    continue;
                else{
                    aflag=1;
                    break;
                }
                         
            }
            
            char c='a';
            if(mobile.length()!=0){
             c= mobile.charAt(0);
            }           
            
            if(mobile.length()>11 || mobile.length()<11 || c!='0'){
                mflag=1;
            }
            
            for(int i=0 ; i<mobile.length() ; i++){
                 c= mobile.charAt(i);
                
                if(c>='0' && c<='9')
                    continue;
                else{
                    mflag=1;
                    break;
                }
                         
            }
            
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM Userr WHERE UserEmail = '"+email+"'");
            
            
            if (resultSet.next()) {
                 uflag =1;
                
            }
            
            
            

            if (email.equals("") || name.equals("") || age.equals("") || address.equals("") || mobile.equals("") || password.equals("") || confirmpassword.equals("") || bloodgroup.equals("Select") || gender.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please insert all informations");
            } else if (!password.equals(confirmpassword)) {
                JOptionPane.showMessageDialog(this, "Password doesn't match");
            } 
            else if(!b){
                JOptionPane.showMessageDialog(this, "Incorrect Email Format");
            }
            else if(uflag==1){
                JOptionPane.showMessageDialog(this, "User Already Exists");
            }
            
            else if(aflag==1){
                JOptionPane.showMessageDialog(this, "Insert Valid Age");
            }
            
            else if(mflag==1){
                JOptionPane.showMessageDialog(this, "Insert Valid Mobile No");
            }
            
            else {
                 
                JOptionPane.showMessageDialog(this, "Signed UP!");
                Login ob = new Login();
                ob.setVisible(true);
                dispose();
                 statement = connection.createStatement();
                 resultSet = statement.executeQuery("SELECT * FROM Userr");

                while (resultSet.next()) {
                    cnt++;
                }

               
                cnt++;
                System.out.println(cnt);
                String id = Integer.toString(cnt);
               
                flag=1;
                statement.executeQuery("INSERT INTO Userr(UserId, UserEmail , UserName, UserGender, UserAge, UserAddress , UserBloodGroup, UserMobileNo, UserCovidStatus, UserPassword) VALUES ( " + cnt + " , '" + email + "' , '" + name + "' , '" + gender + "' , " + Integer.parseInt(age) + " , '" + address + "' , '" + bloodgroup + "' , '" + mobile + "' , '" + covidstatus + "' , '" + password + "')");
                
                
            }

            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(flag==1){
          try{
            Statement statement = connection.createStatement();
            statement.executeQuery("INSERT INTO Plasma (UserID, DonationStatus) VALUES (" + cnt + ", 'No')");
            flag=0;
            connection.close();
            
            
          }catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
        
    }//GEN-LAST:event_signupButtonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        Login ob = new Login();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void usernameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextfieldActionPerformed
        
    }//GEN-LAST:event_usernameTextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel title;
    private javax.swing.JLabel useraddressLabel;
    private javax.swing.JTextField useraddressTextfield;
    private javax.swing.JLabel userageLabel;
    private javax.swing.JTextField userageTextfield;
    private javax.swing.JLabel userbloodgroupLabel;
    private javax.swing.JComboBox<String> userbloodgroupTextfield;
    private javax.swing.JLabel userconfirmpasswordLabel;
    private javax.swing.JPasswordField userconfirmpasswordTextfield;
    private javax.swing.JLabel useremailLabel;
    private javax.swing.JTextField useremailTextfield;
    private javax.swing.JLabel usergenderLabel;
    private javax.swing.JComboBox<String> usergenderTextfield;
    private javax.swing.JLabel usermobileLabel;
    private javax.swing.JTextField usermobileTextfield;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextfield;
    private javax.swing.JLabel userpasswordLabel;
    private javax.swing.JPasswordField userpasswordTextfield;
    // End of variables declaration//GEN-END:variables
}
