/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19helpline;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     */
    String usid, date1, date2, covidstatus;

    public UserProfile() {
        initComponents();
    }

    public UserProfile(String mg) {
        initComponents();

        usid = mg;

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=COVID19 Helpline;selectMethod=cursor", "sa", "123456");

            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM Userr WHERE UserId = '" + mg + "'");

            if (resultSet.next()) {

                String email = resultSet.getString("UserEmail");
                jemail.setText(email);

                String name = resultSet.getString("UserName");
                jname.setText(name);

                String gender = resultSet.getString("UserGender");
                jgender.setText(gender);

                String address = resultSet.getString("UserAddress");
                jaddress.setText(address);

                String bg = resultSet.getString("UserBloodGroup");
                jbloodgroup.setText(bg);

                String mn = resultSet.getString("UserMobileNo");
                jphoneno.setText(mn);

                String age = String.valueOf(resultSet.getInt("UserAge"));
                jage.setText(age);

                covidstatus = resultSet.getString("UserCovidStatus");
                jcovidstatus.setText(covidstatus);
                if (covidstatus.equals("Not Affected")) {
                    jcovidstatus.setForeground(Color.decode("#006400"));
                    jLabel10.setVisible(false);
                    jaffecteddate.setVisible(false);
                    jLabel11.setVisible(false);
                    jrecoverydate.setVisible(false);
                } else {
                    jcovidstatus.setForeground(Color.RED);
                    jLabel10.setVisible(true);
                    jaffecteddate.setVisible(true);

                    jLabel11.setVisible(true);
                    jrecoverydate.setVisible(true);

                    date1 = resultSet.getString("UserAffectedDate");
                    jaffecteddate.setText(date1);

                    date2 = resultSet.getString("UserRecoveryDate");

                    if (date2.equals(null)) {
                        jLabel11.setVisible(false);
                        jrecoverydate.setVisible(false);

                    } else {
                        jLabel11.setVisible(true);
                        jrecoverydate.setText(date2);
                    }

                    jrecoverydate.setText(date2);

                    if (date1 != null && date2 != null) {
                        updatecovidinfobutton.setVisible(false);
                    }
                }

            }

            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        useraffecteddateLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        updatepersonalinfobutton = new javax.swing.JButton();
        updatecovidinfobutton = new javax.swing.JButton();
        backdashboardbutton = new javax.swing.JButton();
        jname = new javax.swing.JLabel();
        jemail = new javax.swing.JLabel();
        jgender = new javax.swing.JLabel();
        jage = new javax.swing.JLabel();
        jaddress = new javax.swing.JLabel();
        jbloodgroup = new javax.swing.JLabel();
        jphoneno = new javax.swing.JLabel();
        jcovidstatus = new javax.swing.JLabel();
        jaffecteddate = new javax.swing.JLabel();
        jrecoverydate = new javax.swing.JLabel();
        seemessageButton = new javax.swing.JButton();
        seepurchaseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("User Profile");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel4.setText("Gender:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setText("Age:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setText("Address:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setText("Blood Group:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel8.setText("Phone No:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel9.setText("Covid19 Status:");

        useraffecteddateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel10.setText("Covid19 Affected Date:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel11.setText("Covid19 Recovery Date:");

        updatepersonalinfobutton.setBackground(new java.awt.Color(0, 0, 255));
        updatepersonalinfobutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        updatepersonalinfobutton.setForeground(new java.awt.Color(255, 255, 255));
        updatepersonalinfobutton.setText("Update Personal Info");
        updatepersonalinfobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepersonalinfobuttonActionPerformed(evt);
            }
        });

        updatecovidinfobutton.setBackground(new java.awt.Color(255, 0, 0));
        updatecovidinfobutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        updatecovidinfobutton.setForeground(new java.awt.Color(255, 255, 255));
        updatecovidinfobutton.setText("Update COVID Info");
        updatecovidinfobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecovidinfobuttonActionPerformed(evt);
            }
        });

        backdashboardbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backdashboardbutton.setText("Back To Dashboard");
        backdashboardbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backdashboardbuttonActionPerformed(evt);
            }
        });

        jname.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jname.setText("Name:");

        jemail.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jemail.setText("Emai:");

        jgender.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jgender.setText("Gender:");

        jage.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jage.setText("Age:");

        jaddress.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jaddress.setText("Address:");

        jbloodgroup.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jbloodgroup.setText("Blood Group:");

        jphoneno.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jphoneno.setText("Phone No:");

        jcovidstatus.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jcovidstatus.setText("Covid19 Status:");

        jaffecteddate.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jaffecteddate.setText("Covid19 Affected Date:");

        jrecoverydate.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jrecoverydate.setText("Not Yet Recoverd");

        seemessageButton.setBackground(new java.awt.Color(51, 153, 0));
        seemessageButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        seemessageButton.setForeground(new java.awt.Color(255, 255, 255));
        seemessageButton.setText("See your messages");
        seemessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seemessageButtonActionPerformed(evt);
            }
        });

        seepurchaseButton.setBackground(new java.awt.Color(51, 153, 0));
        seepurchaseButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        seepurchaseButton.setForeground(new java.awt.Color(255, 255, 255));
        seepurchaseButton.setText("Purchase History");
        seepurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seepurchaseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jgender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jrecoverydate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jaddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbloodgroup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jphoneno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcovidstatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jaffecteddate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(useraffecteddateLabel)
                                    .addComponent(updatepersonalinfobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(seemessageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updatecovidinfobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(seepurchaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(backdashboardbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jgender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jaddress))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jbloodgroup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jphoneno))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcovidstatus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jaffecteddate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jrecoverydate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(useraffecteddateLabel)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatepersonalinfobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatecovidinfobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seemessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seepurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(backdashboardbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backdashboardbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backdashboardbuttonActionPerformed
        setVisible(false);
        dashboard db = new dashboard(usid);
        db.setVisible(true);
    }//GEN-LAST:event_backdashboardbuttonActionPerformed

    private void updatepersonalinfobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepersonalinfobuttonActionPerformed
        setVisible(false);
        UpdateProfile db = new UpdateProfile(usid);
        db.setVisible(true);
    }//GEN-LAST:event_updatepersonalinfobuttonActionPerformed

    private void updatecovidinfobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecovidinfobuttonActionPerformed

        if (covidstatus.equals("Not Affected")) {
            setVisible(false);
            UpdateCovidInfo db = new UpdateCovidInfo(usid);
            db.setVisible(true);
        } else {
            setVisible(false);
            coviddateselect cs = new coviddateselect(usid);
            cs.setVisible(true);

        }

    }//GEN-LAST:event_updatecovidinfobuttonActionPerformed

    private void seemessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seemessageButtonActionPerformed
       setVisible(false);
       UserInbox ob = new UserInbox(usid);
       ob.setVisible(true);
    }//GEN-LAST:event_seemessageButtonActionPerformed

    private void seepurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seepurchaseButtonActionPerformed
        setVisible(false);
        UserPurchase ob = new UserPurchase(usid);
        ob.setVisible(true);
    }//GEN-LAST:event_seepurchaseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backdashboardbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jaddress;
    private javax.swing.JLabel jaffecteddate;
    private javax.swing.JLabel jage;
    private javax.swing.JLabel jbloodgroup;
    private javax.swing.JLabel jcovidstatus;
    private javax.swing.JLabel jemail;
    private javax.swing.JLabel jgender;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jphoneno;
    private javax.swing.JLabel jrecoverydate;
    private javax.swing.JButton seemessageButton;
    private javax.swing.JButton seepurchaseButton;
    private javax.swing.JButton updatecovidinfobutton;
    private javax.swing.JButton updatepersonalinfobutton;
    private javax.swing.JLabel useraffecteddateLabel;
    // End of variables declaration//GEN-END:variables
}
